name: daily-status

on:
  schedule:
    - cron: "20 0 * 4,5,6,7,8,9,10 *"
    - cron: "20 1 * 11,12 *"
    - cron: "20 1 * 1,2,3 *"
  workflow_dispatch: {}

concurrency:
  group: daily-status
  cancel-in-progress: true

permissions:
  contents: write
  issues: write

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      QELM_START_DATE: "2024-11-28"
      STATUS_FILE: "STATUS.md"
      MILESTONES_FILE: "STATUS_MILESTONES.json"
      TIMEZONE: "America/Anchorage"
      MAX_COMMITS_PER_DAY: "3"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: python -m pip install --upgrade pip requests

      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python scripts/update_milestones.py

      - run: python scripts/update_status.py

      - name: commit & push
        run: |
          set -e
          if git diff --quiet; then
            echo "no file changes"; exit 0
          fi
          git config user.name "qelm-status-bot"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          msg=$(head -n 1 "$STATUS_FILE" || echo "status")
          git commit -m "chore(status): ${msg}"
          git push --force-with-lease origin main
