name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --ignore=F821 --show-source --statistics
        flake8 . --count --exit-zero --ignore=F821 --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest || [ $? -eq 5 ]

    - name: Install Xvfb
      run: sudo apt-get install -y xvfb

    - name: Run Python script with virtual display
      run: timeout 120 xvfb-run python QelmT.py || [ $? -eq 124 ]
