name: release-qelm

on:
  push:
    tags:
      - 'v*'   # e.g. v0.1.1

permissions:
  contents: read  

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'   

      - name: Clean previous builds
        run: rm -rf dist build *.egg-info

      - name: Install build backend
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build distributions
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true  
